layout_spectrum: 0.6718195573489486
typography_spectrum: 0.3953637053928163
color:
  brandStrength: 0.5490521073803343
  lightness: 0.264870876981093
  saturation: 0.8344561465118671
  rhythmicContrast: 0.7921981832405349
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
analytics:
  google: UA-90359424-1
  twitter: '#avatarbrain'
author:
  email: 'Twitter: @olairet'
  name: Oswaldo Lairet
  url: 'https://www.facebook.com/InformationSymmetry'
name: Avatar-Brain
url: 'http://avatarbrain.com'
navigation:
  - name: Hack The Matrix
    url: 'http://www.infoasy.com/2016/07/hack-matrix.html'
    type: external
  - name: Huarache Runners
    url: 'https://www.strava.com/clubs/huarache-runners'
    type: external
  - name: Open Source Capitalism
    url: 'https://www.facebook.com/InformationSymmetry'
    type: external
title: The beholder within
content: []
description: >-
  Increasing the odds of finding happiness for ourselves, our families, and
  communities by learning how to preserve Cerebral, Physical, Financial and
  Social Health
