typography_spectrum: 0.3953637053928163
color:
  brandStrength: 0.5490521073803343
  lightness: 0.264870876981093
  saturation: 0.8344561465118671
  rhythmicContrast: 0.7921981832405349
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
layout_spectrum: 0.6718195573489486
analytics:
  google: UA-90359424-1
  twitter: '#avatarbrain'
author:
  email: 'Twitter: @olairet'
  name: Oswaldo Lairet
  url: 'https://www.facebook.com/InformationSymmetry'
name: Avatar Brain
url: 'http://avatarbrain.com'
navigation:
  - name: Hack The Matrix
    url: 'http://www.infoasy.com/2016/07/hack-matrix.html'
    type: external
  - name: Huarache Runners
    url: 'https://www.strava.com/clubs/huarache-runners'
    type: external
  - name: Information Asymmetry
    url: 'http://sequoian.com/wp-content/uploads/2017/08/Information_Symmetry.pdf'
    type: external
  - name: Predator-Prey Economics
    url: >-
      http://sequoian.com/2017/08/wp-contentuploads201710predator-prey-economics-reloaded-pdf/
    type: external
title: The beholder within
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: interactive
    html: >-
      <iframe
      src="https://drive.google.com/viewerng/viewer?url=http%3A//sequoian.com/wp-content/uploads/2017/08/Predator-Prey2.pdf&embedded=true"
      width="600" height="780"></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'http://sequoian.com/wp-content/uploads/2017/08/Predator-Prey2.pdf'
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'http://sequoian.com'
        name: Sequoian
        favicon: null
        domain: sequoian.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/21842b23-88c4-485a-b3a2-6b2f18d79065.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/21842b23-88c4-485a-b3a2-6b2f18d79065.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  If our brain is a web-server in an idea-network (culture), identical
  perceptual experiences would cause a myriad interpretations and with each, a
  different destiny
