layout_spectrum: 0.33065799857406775
typography_spectrum: 0.0634826456495367
color:
  brandStrength: 0.2564849087410597
  lightness: 0.33650049051233005
  saturation: 0.7453368956357757
  rhythmicContrast: 0.1962456757388087
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
author:
  email: olairet@sequoian.com
  name: Oswaldo Lairet
  url: 'http://sequoian.com/'
name: Avatar-Brain
url: 'https://thegrid.ai/avatar-brain/'
title: The beholder within us
content: []
description: >-
  Our mission is to teach as many people as possible how to preserve their
  Cerebral, Physical, Financial, and Social Health and thus, increase their
  chances of finding happiness for themselves, their families, and their
  community. 
