typography_spectrum: 0.40136745410123015
color:
  brandStrength: 0.772417243597568
  lightness: 0.5118557413033957
  saturation: 0.09439741927208287
  rhythmicContrast: 0.6737022887332605
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
layout_spectrum: 0.2962039427662102
author:
  email: ''
  name: We Are Our Brain's Avatar
  url: 'http://www.infoasy.com/2016/07/hack-matrix_29.html'
name: Avatar-Brain
url: 'http://avatarbrain.com'
navigation:
  - name: Hack The Matrix
    url: 'http://www.infoasy.com/2016/07/hack-matrix_29.html'
    type: external
  - name: Huarache Runners
    url: 'https://www.strava.com/clubs/huarache-runners'
    type: external
  - name: Information Asymmetry
    url: 'http://sequoian.com/wp-content/uploads/2016/03/Information-Symmetry.pdf'
    type: external
  - name: Open Source Capitalism
    url: 'https://www.facebook.com/InformationSymmetry'
    type: external
title: the beholder within..
content: []
description: >-
  Our mission is to increase the odds of finding happiness for ourselves, our
  families, and communities by learning how to preserve Cerebral, Physical,
  Financial and Social Health
