typography_spectrum: 0.43971961071216825
color:
  brandStrength: 0.7757130775455902
  lightness: 0.4472101909220034
  saturation: 0.09359393434718914
  rhythmicContrast: 0.48634437502075983
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
layout_spectrum: 0.2916472777236474
author:
  email: ''
  name: We Are Our Brain's Avatar
  url: 'http://sequoian.com/'
name: Avatar-Brain
url: 'https://thegrid.ai/avatar-brain/'
navigation:
  - name: We Are Our Brain's Avatar
    url: 'http://www.infoasy.com/2016/07/hack-matrix_29.html'
    type: external
  - name: Open Source Capitalism
    url: 'https://www.facebook.com/InformationSymmetry'
    type: external
title: The beholder inside us
content: []
description: >-
  Our mission is to teach as many people as possible how to preserve their
  Cerebral, Physical, Financial, and Social Health and thus, increase their
  chances of finding happiness for themselves, their families, and their
  community. 
