typography_spectrum: 0.20824317634105682
color:
  brandStrength: 0.6659516380168498
  lightness: 0.9434288372285664
  saturation: 0.053200821159407496
  rhythmicContrast: 0.3138160044327378
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
github: true
layout_spectrum: 0.5755517303477973
author:
  email: olairet@sequoian.com
  name: Oswaldo Lairet
  url: 'http://sequoian.com/'
name: Avatar-Brain
url: 'https://thegrid.ai/avatar-brain/'
title: The beholder inside us
content: []
description: >-
  Our mission is to teach as many people as possible, how to stay long-term
  healthy in those four areas and hopefully, grow their chances of finding
  happiness for themselves, their families, and their communities
