layout_spectrum: 0.2949099548291046
typography_spectrum: 0.43175090733048793
color:
  brandStrength: 0.7721906783158826
  lightness: 0.44864522852750477
  saturation: 0.09586870535839312
  rhythmicContrast: 0.48718141764190304
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
author:
  email: ''
  name: We Are Our Brain's Avatar
  url: 'http://www.infoasy.com/2016/07/hack-matrix_29.html'
name: Avatar-Brain
url: 'https://thegrid.ai/avatar-brain/'
navigation:
  - name: Hack The Matrix
    url: 'http://www.infoasy.com/2016/07/hack-matrix_29.html'
    type: external
  - name: Huarache Runners
    url: 'https://www.strava.com/clubs/huarache-runners'
    type: external
  - name: Information Asymmetry
    url: 'http://sequoian.com/wp-content/uploads/2016/03/Information-Symmetry.pdf'
    type: external
  - name: Open Source Capitalism
    url: 'https://www.facebook.com/InformationSymmetry'
    type: external
title: The beholder within us
content: []
description: >-
  Our mission is to teach as many people as possible, how to increase their
  chances of finding happiness for themselves, their families, and their
  communities by preserving their Cerebral, Physical, Financial, and Social
  Health
