typography_spectrum: 0.06019708726702645
color:
  brandStrength: 0.7754032189315093
  lightness: 0.44390313146866417
  saturation: 0.7421219372906086
  rhythmicContrast: 0.19470676325206268
  brandColors:
    - '#909DAE'
    - '#1E2C42'
    - '#560A19'
    - '#C54831'
    - '#BAC5C9'
github: true
layout_spectrum: 0.2991070036915601
author:
  email: olairet@sequoian.com
  name: Oswaldo Lairet
  url: 'http://sequoian.com/'
name: Avatar-Brain
url: 'https://thegrid.ai/avatar-brain/'
title: The beholder inside us
content: []
description: >-
  Our mission: Teach as many people as possible how to preserve their Cerebral,
  Physical, Financial, and Social Health and thus, increase their chances of
  finding happiness for themselves, their families, and their community. 
