layout_spectrum: 0.6714311454885888
typography_spectrum: 0.021423785539048883
color:
  brandStrength: 0.770046947632114
  lightness: 0.5125987988222612
  saturation: 0.15686383364021336
  rhythmicContrast: 0.19328648652383448
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
github: true
analytics:
  google: UA-90359424-1
  twitter: '#avatarbrain'
author:
  email: 'Twitter: @olairet'
  name: Oswaldo Lairet
  url: 'https://www.facebook.com/InformationSymmetry'
name: Avatar Brain
url: 'http://avatarbrain.com'
navigation:
  - name: Hack The Matrix
    url: 'http://www.infoasy.com/2016/07/hack-matrix.html'
    type: external
  - name: Huarache Runners
    url: 'https://www.strava.com/clubs/huarache-runners'
    type: external
  - name: Information Asymmetry
    url: >-
      http://sequoian.com/2016/03/wp-contentuploads201708information_symmetry-pdf/
    type: external
  - name: Predator-Prey Economics
    url: >-
      http://sequoian.com/2017/08/wp-contentuploads201710predator-prey-economics-reloaded-pdf/
    type: external
  - name: The Discount-Rate Pyramid Scheme
    url: >-
      http://sequoian.com/2015/09/wp-contentuploads201610the-discount-rate-pyramid-scheme-2-0-pdf/
    type: external
title: The beholder within
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: interactive
    html: >-
      <iframe
      src="https://drive.google.com/viewerng/viewer?url=http%3A//sequoian.com/wp-content/uploads/2017/08/Predator-Prey2.pdf&embedded=true"
      width="600" height="780"></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'http://sequoian.com/wp-content/uploads/2017/08/Predator-Prey2.pdf'
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'http://sequoian.com'
        name: Sequoian
        favicon: null
        domain: sequoian.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/21842b23-88c4-485a-b3a2-6b2f18d79065.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/21842b23-88c4-485a-b3a2-6b2f18d79065.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  cultural codes filter identical perceptual experiences in slightly different
  ways, each leading to unique, even antithetical destinies
